slices = "["
.."  ["
.."    ["
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"DashedStiched\","
.."          \"Left\": \"Solid\","
.."          \"Right\": \"Solid\","
.."          \"Top\": \"Dashed\""
.."        },"
.."        \"patch_type\": \"Qubit\","
.."        \"text\": \"Id: 0\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"Dashed\","
.."          \"Left\": \"Solid\","
.."          \"Right\": \"Solid\","
.."          \"Top\": \"Dashed\""
.."        },"
.."        \"patch_type\": \"Qubit\","
.."        \"text\": \"Id: 1\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"Dashed\","
.."          \"Left\": \"Solid\","
.."          \"Right\": \"Solid\","
.."          \"Top\": \"Dashed\""
.."        },"
.."        \"patch_type\": \"Qubit\","
.."        \"text\": \"Id: 2\""
.."      },"
.."      null,"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"DashedStiched\","
.."          \"Left\": \"Solid\","
.."          \"Right\": \"Solid\","
.."          \"Top\": \"Dashed\""
.."        },"
.."        \"patch_type\": \"Qubit\","
.."        \"text\": \"Id: 6\""
.."      },"
.."      null,"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"Solid\","
.."          \"Right\": \"None\","
.."          \"Top\": \"Solid\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"Time to next magic state:10\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"None\","
.."          \"Right\": \"None\","
.."          \"Top\": \"Solid\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"None\","
.."          \"Right\": \"None\","
.."          \"Top\": \"Solid\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"None\","
.."          \"Right\": \"None\","
.."          \"Top\": \"Solid\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"None\","
.."          \"Right\": \"Solid\","
.."          \"Top\": \"Solid\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      }"
.."    ],"
.."    ["
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"None\","
.."          \"Right\": \"AncillaJoin\","
.."          \"Top\": \"AncillaJoin\""
.."        },"
.."        \"patch_type\": \"Ancilla\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"AncillaJoin\","
.."          \"Right\": \"AncillaJoin\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"Ancilla\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"AncillaJoin\","
.."          \"Right\": \"AncillaJoin\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"Ancilla\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"AncillaJoin\","
.."          \"Right\": \"AncillaJoin\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"Ancilla\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"AncillaJoin\","
.."          \"Right\": \"None\","
.."          \"Top\": \"AncillaJoin\""
.."        },"
.."        \"patch_type\": \"Ancilla\","
.."        \"text\": \"\""
.."      },"
.."      null,"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"Solid\","
.."          \"Right\": \"None\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"None\","
.."          \"Right\": \"None\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"None\","
.."          \"Right\": \"None\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"None\","
.."          \"Right\": \"None\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"None\","
.."          \"Right\": \"Solid\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      }"
.."    ],"
.."    ["
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"Dashed\","
.."          \"Left\": \"Solid\","
.."          \"Right\": \"Solid\","
.."          \"Top\": \"Dashed\""
.."        },"
.."        \"patch_type\": \"Qubit\","
.."        \"text\": \"Id: 3\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"Dashed\","
.."          \"Left\": \"Solid\","
.."          \"Right\": \"Solid\","
.."          \"Top\": \"Dashed\""
.."        },"
.."        \"patch_type\": \"Qubit\","
.."        \"text\": \"Id: 4\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"Dashed\","
.."          \"Left\": \"Solid\","
.."          \"Right\": \"Solid\","
.."          \"Top\": \"Dashed\""
.."        },"
.."        \"patch_type\": \"Qubit\","
.."        \"text\": \"Id: 5\""
.."      },"
.."      null,"
.."      null,"
.."      null,"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"Solid\","
.."          \"Left\": \"Solid\","
.."          \"Right\": \"None\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"Solid\","
.."          \"Left\": \"None\","
.."          \"Right\": \"None\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"Solid\","
.."          \"Left\": \"None\","
.."          \"Right\": \"None\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"Solid\","
.."          \"Left\": \"None\","
.."          \"Right\": \"None\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"Solid\","
.."          \"Left\": \"None\","
.."          \"Right\": \"Solid\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      }"
.."    ]"
.."  ],"
.."  ["
.."    ["
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"Dashed\","
.."          \"Left\": \"Solid\","
.."          \"Right\": \"Solid\","
.."          \"Top\": \"Dashed\""
.."        },"
.."        \"patch_type\": \"Qubit\","
.."        \"text\": \"Id: 0\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"Dashed\","
.."          \"Left\": \"Solid\","
.."          \"Right\": \"Solid\","
.."          \"Top\": \"Dashed\""
.."        },"
.."        \"patch_type\": \"Qubit\","
.."        \"text\": \"Id: 1\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"Dashed\","
.."          \"Left\": \"Solid\","
.."          \"Right\": \"Solid\","
.."          \"Top\": \"Dashed\""
.."        },"
.."        \"patch_type\": \"Qubit\","
.."        \"text\": \"Id: 2\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"AncillaJoin\","
.."          \"Left\": \"None\","
.."          \"Right\": \"AncillaJoin\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"Ancilla\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"Dashed\","
.."          \"Left\": \"SolidStiched\","
.."          \"Right\": \"Solid\","
.."          \"Top\": \"Dashed\""
.."        },"
.."        \"patch_type\": \"Qubit\","
.."        \"text\": \"Id: 6\""
.."      },"
.."      null,"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"Solid\","
.."          \"Right\": \"None\","
.."          \"Top\": \"Solid\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"Time to next magic state:9\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"None\","
.."          \"Right\": \"None\","
.."          \"Top\": \"Solid\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"None\","
.."          \"Right\": \"None\","
.."          \"Top\": \"Solid\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"None\","
.."          \"Right\": \"None\","
.."          \"Top\": \"Solid\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"None\","
.."          \"Right\": \"Solid\","
.."          \"Top\": \"Solid\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      }"
.."    ],"
.."    ["
.."      null,"
.."      null,"
.."      null,"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"AncillaJoin\","
.."          \"Left\": \"None\","
.."          \"Right\": \"None\","
.."          \"Top\": \"AncillaJoin\""
.."        },"
.."        \"patch_type\": \"Ancilla\","
.."        \"text\": \"\""
.."      },"
.."      null,"
.."      null,"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"Solid\","
.."          \"Right\": \"None\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"None\","
.."          \"Right\": \"None\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"None\","
.."          \"Right\": \"None\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"None\","
.."          \"Right\": \"None\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"None\","
.."          \"Right\": \"Solid\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      }"
.."    ],"
.."    ["
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"Dashed\","
.."          \"Left\": \"Solid\","
.."          \"Right\": \"Solid\","
.."          \"Top\": \"Dashed\""
.."        },"
.."        \"patch_type\": \"Qubit\","
.."        \"text\": \"Id: 3\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"Dashed\","
.."          \"Left\": \"Solid\","
.."          \"Right\": \"Solid\","
.."          \"Top\": \"Dashed\""
.."        },"
.."        \"patch_type\": \"Qubit\","
.."        \"text\": \"Id: 4\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"Dashed\","
.."          \"Left\": \"Solid\","
.."          \"Right\": \"SolidStiched\","
.."          \"Top\": \"Dashed\""
.."        },"
.."        \"patch_type\": \"Qubit\","
.."        \"text\": \"Id: 5\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"None\","
.."          \"Left\": \"AncillaJoin\","
.."          \"Right\": \"None\","
.."          \"Top\": \"AncillaJoin\""
.."        },"
.."        \"patch_type\": \"Ancilla\","
.."        \"text\": \"\""
.."      },"
.."      null,"
.."      null,"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"Solid\","
.."          \"Left\": \"Solid\","
.."          \"Right\": \"None\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"Solid\","
.."          \"Left\": \"None\","
.."          \"Right\": \"None\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"Solid\","
.."          \"Left\": \"None\","
.."          \"Right\": \"None\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"Solid\","
.."          \"Left\": \"None\","
.."          \"Right\": \"None\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      },"
.."      {"
.."        \"activity\": {"
.."          \"activity_type\": null"
.."        },"
.."        \"edges\": {"
.."          \"Bottom\": \"Solid\","
.."          \"Left\": \"None\","
.."          \"Right\": \"Solid\","
.."          \"Top\": \"None\""
.."        },"
.."        \"patch_type\": \"DistillationQubit\","
.."        \"text\": \"\""
.."      }"
.."    ]"
.."  ]"
.."]"
